apiVersion: v1
entries:
  l7mp-ingress:
  - apiVersion: v2
    created: "2020-11-17T16:33:32.949012789Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 32638252784dd2f5e52e7bbe2898948648941a01263322e3574020edcbe35eac
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    created: "2020-11-17T16:33:32.94545037Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 2974ce1dc133294376cd764022807aa9c016c3b2cd937bdf39a9d5b2bc2c7ea8
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    created: "2020-11-17T16:33:32.922252327Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 5e49d9f67ce9b4a8e0d9e14c6fd78d8ad1a39ed7b512e8cb96dabdc503ebb5de
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    created: "2020-11-17T16:33:32.891957508Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.3
    description: Ingress gateways for the l7mp service mesh
    digest: 6da6e824c4aa3a2642eec09571d7b20705f9776a7073e505d00ad77c914a2825
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    created: "2020-11-17T16:33:32.88814751Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.2
    description: Ingress gateways for the l7mp service mesh
    digest: 7aa8a3647b7354a348ecf9ba45bd6ac199dd3b0d26368f6f7d2463dd4695602c
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.2.tgz
    version: 0.1.2
  l7mp-operator:
  - apiVersion: v2
    created: "2020-11-17T16:33:32.987522943Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: acc4cf41429beac827089c9499446023cc45fac0ed0b6ad6ce23fdb104972c50
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    created: "2020-11-17T16:33:32.98458448Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: a6a8813527e52a79c73bd41c20e189b515f082169d51b67399fe8fe96c245142
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    created: "2020-11-17T16:33:32.980711106Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 8c8367ae2ed8d88c679d9afbe29e4bbe54d85764736a44d1c80b1b37006975f5
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    created: "2020-11-17T16:33:32.973462592Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 0e55569e16ba640fc03c6137aaaf1ea023066d2bd2d0b992f318f757b14c8350
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.1.tgz
    version: 0.1.1
  l7mp-prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-11-17T16:33:33.00886776Z"
    description: A Helm chart for monitoring L7MP, a multiprotocol servicemesh
    digest: f66a036fe42e2013fbdcd3c4434255929ac53fa3d3187f94720b999d7894a82d
    name: l7mp-prometheus
    type: application
    urls:
    - l7mp-prometheus-0.1.0.tgz
    version: 0.1.0
  op-l7mp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-11-17T16:33:33.016418631Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 259ed832c2e571b61f97534cd1dd69a00ea23ac974588037136041ddd1a758cc
    name: op-l7mp
    type: application
    urls:
    - op-l7mp-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-17T16:33:32.846292792Z"
