apiVersion: v1
entries:
  l7mp-ingress:
  - apiVersion: v2
    created: "2020-11-19T14:06:23.711376473Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 96556ece4f08a691b53ff7cb3def6631e1010608211c27f4df3e78d309121ce2
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    created: "2020-11-19T14:06:23.708284515Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 2974ce1dc133294376cd764022807aa9c016c3b2cd937bdf39a9d5b2bc2c7ea8
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    created: "2020-11-19T14:06:23.701163256Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.4
    description: Ingress gateways for the l7mp service mesh
    digest: 5e49d9f67ce9b4a8e0d9e14c6fd78d8ad1a39ed7b512e8cb96dabdc503ebb5de
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    created: "2020-11-19T14:06:23.696972694Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.3
    description: Ingress gateways for the l7mp service mesh
    digest: 6da6e824c4aa3a2642eec09571d7b20705f9776a7073e505d00ad77c914a2825
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    created: "2020-11-19T14:06:23.691681364Z"
    dependencies:
    - name: l7mp-operator
      repository: https://l7mp.io/charts
      version: 0.1.2
    description: Ingress gateways for the l7mp service mesh
    digest: 7aa8a3647b7354a348ecf9ba45bd6ac199dd3b0d26368f6f7d2463dd4695602c
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-ingress
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-ingress-0.1.2.tgz
    version: 0.1.2
  l7mp-operator:
  - apiVersion: v2
    created: "2020-11-19T14:06:23.755236375Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: cc81bbf1da378f2c26ab7e5a031b347702fcf02a61f0b0f8669262ba6f575a75
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    created: "2020-11-19T14:06:23.750330805Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: a6a8813527e52a79c73bd41c20e189b515f082169d51b67399fe8fe96c245142
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    created: "2020-11-19T14:06:23.742995135Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 8c8367ae2ed8d88c679d9afbe29e4bbe54d85764736a44d1c80b1b37006975f5
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    created: "2020-11-19T14:06:23.728752951Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 0e55569e16ba640fc03c6137aaaf1ea023066d2bd2d0b992f318f757b14c8350
    home: https://l7mp.io
    icon: https://l7mp.io/assets/brand/logo.svg
    maintainers:
    - email: nemethf@tmit.bme.hu
      name: Felicián Németh
    name: l7mp-operator
    sources:
    - https://github.com/l7mp/l7mp
    type: application
    urls:
    - l7mp-operator-0.1.1.tgz
    version: 0.1.1
  l7mp-prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-11-19T14:06:23.770778105Z"
    description: A Helm chart for monitoring L7MP, a multiprotocol servicemesh
    digest: 7930868ed4e4255b968c9abeb3b02c5115918276d9bc52c20937e016f68e8be9
    name: l7mp-prometheus
    type: application
    urls:
    - l7mp-prometheus-0.1.0.tgz
    version: 0.1.0
  op-l7mp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-11-19T14:06:23.787300014Z"
    description: Operator handling CRDs of the l7mp service mesh
    digest: 259ed832c2e571b61f97534cd1dd69a00ea23ac974588037136041ddd1a758cc
    name: op-l7mp
    type: application
    urls:
    - op-l7mp-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-19T14:06:23.687380286Z"
